name: HeroLFG Page Build Discord Notif
on: [page_build]
jobs:
  Share-Page-Build-With-Discord-Server:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - uses: actions/checkout@v2
      - run: echo "using https://github.com/marketplace/actions/actions-for-discord"
      - name: Discord Notification actions-for-discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_HEROLFG_PLAYGROUND_WEBHOOK }}
          DISCORD_USERNAME: 'Page Build Status'
          DISCORD_AVATAR: 'https://avatars.githubusercontent.com/u/9197206?v=4'
          DISCORD_EMBEDS: '[{"title":"${{ event.build.status }}","color":1127128},{"title":"https://github.com/heroLFG/herolfg.com/actions"}]'
        uses: Ilshidur/action-discord@08d9328877d6954120eef2b07abbc79249bb6210
