name: HeroLFG Page Build Discord Notif
on: [page_build]
jobs:
  Share-Page-Build-With-Discord-Server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "using https://github.com/marketplace/actions/actions-for-discord"
      - name: Discord Notification actions-for-discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_HEROLFG_PLAYGROUND_WEBHOOK }}
        uses: Ilshidur/action-discord@08d9328877d6954120eef2b07abbc79249bb6210
        with:
          args: '{{ EVENT_PAYLOAD.repository.full_name }} build status: {{ EVENT_PAYLOAD.status }} and comment: {{ github.event.head_commit.message }}'
