name: HeroLFG Push Discord Notif
on: [push]
jobs:
  Share-Push-With-Discord-Server:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Diff Ignore .github
        id: git_diff
        run: echo "::set-output name=diff::$(git diff HEAD HEAD^ --name-only -- :^.github)"
      - name: Diff Not Ignore .github
        id: git_diff_no_ignore
        run: echo "::set-output name=diff::$(git diff HEAD HEAD^)"
      - name: dump env context
        run: echo '${{ toJSON(env) }}'
      - name: dump job context
        run: echo '${{ toJSON(job) }}'
      - name: dump steps context
        run: echo '${{ toJSON(step) }}'
      - run: echo "using https://github.com/marketplace/actions/actions-for-discord"
      - name: Discord Notification actions-for-discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_HEROLFG_PLAYGROUND_WEBHOOK }}
          # DISCORD_USERNAME: 'Page Push Status'
          # DISCORD_AVATAR: 'https://avatars.githubusercontent.com/u/5564129?v=4'
          DISCORD_AVATAR: 'https://avatars.githubusercontent.com/u/9197206?v=4'
          DISCORD_EMBEDS: '[{"title":"Rebuilding https://herolfg.com"},{"title":"${{ github.event.head_commit.message }}"},{"title":"Wait for build status..."}]'
        uses: Ilshidur/action-discord@08d9328877d6954120eef2b07abbc79249bb6210
        if: git diff HEAD HEAD^ --name-only -- :^.github
