name: HeroLFG Push Discord Notif
on: [push]
jobs:
  Share-Page-Build-With-Discord-Server:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - uses: actions/checkout@v2
      - run: echo "using https://github.com/marketplace/actions/actions-for-discord"
      - name: Discord Notification actions-for-discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_HEROLFG_PLAYGROUND_WEBHOOK }}
          DISCORD_AVATAR: 'https://avatars.githubusercontent.com/u/5564129?v=4'
          DISCORD_EMBEDS: '[{"title":"${{ github.event.head_commit.message }}","color":1127128}]'
        uses: Ilshidur/action-discord@08d9328877d6954120eef2b07abbc79249bb6210
