name: HeroLFG Page Build Discord Notif
on: [page_build]
jobs:
  Share-Page-Build-With-Discord-Server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Diff Ignore .github
        id: git_diff
        run: echo "::set-output name=test::$(git diff HEAD HEAD^ --name-only -- :^.github)"
      - name: git log
        id: git_log
        run: echo "::set-output name=test::$(git log -1 --pretty=format:"%s")"
      - name: decide share
        id: share
        run: echo "::set-output name=test::$(git log -1 --pretty=format:"%s" | grep share:)"
      - name: Diff Not Ignore .github
        id: git_diff_no_ignore
        run: echo "::set-output name=test::$(git diff HEAD HEAD^ --name-only)"
      - name: dump job context
        run: echo '${{ toJSON(job) }}'
      - name: dump steps context
        run: echo '${{ toJSON(steps) }}'
      - run: echo "using https://github.com/marketplace/actions/actions-for-discord"
      - name: Discord Notification actions-for-discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_HEROLFG_PLAYGROUND_WEBHOOK }}
          DISCORD_AVATAR: 'https://avatars.githubusercontent.com/u/9197206?v=4'
          DISCORD_EMBEDS: '[{"title":"update to https://herolfg.com"},{"title":"${{ steps.git_log.outputs.test }}"}]'
        uses: Ilshidur/action-discord@08d9328877d6954120eef2b07abbc79249bb6210
        if: steps.share.outputs.test
        # if: steps.git_diff.outputs.test
